# Root Hyprland config for project-based setup

source = ./variables.conf
source = ./env.conf
source = ./monitors.conf
source = ./input.conf
source = ./aesthetics.conf
source = ./windowrules.conf
source = ./binds.conf
source = ./autostart.conf
