# External
#monitor = DP-1, 3840x2400@120, 0x0, 1

# laptop
#monitor = eDP-1, disabled

#monitor = eDP-1, preferred, auto, 1

# for random monitors
#monitor = , preferred, auto, 1
monitor = eDP-1, preferred, auto, 2, vrr, 1

# workspace=1,monitor:$
#workspace=2,monitor:$
#workspace=3,monitor:$
#workspace=4,monitor:$
#workspace=5,monitor:$
