#################
### AUTOSTART ###
#################

# exec-once = nm-applet
exec-once = swaync
exec-once = waybar -c ~/.config/waybar/config.json
exec-once = swww-daemon
exec-once = kanshi
exec-once = nm-applet
exec-once = swayosd-server --style ~/.config/swayosd/style.css
exec-once = mpd