# Root Hyprland config for project-based setup

source = ~/.config/hypr/themes/synthwave84.conf

source = ./variables.conf
source = ./env.conf
source = ./monitors.conf
source = ./input.conf
source = ./aesthetics.conf
source = ./windowrules.conf
source = ./binds.conf
source = ./autostart.conf

# ── XWayland ───────────────────────────────
xwayland {
    enabled              = true
    use_nearest_neighbor = false
    force_zero_scaling   = false
}

# ── Ecosystem ──────────────────────────────
ecosystem {
    no_update_news = true
}
