# ── Input ──────────────────────────────────
input {
    kb_layout          = pl
    kb_options         = grp:alt_shift_toggle
    sensitivity        = -0.1
    accel_profile      = adaptive
    follow_mouse       = 1
    numlock_by_default = true
    repeat_delay       = 220
    repeat_rate        = 40

    touchpad {
        disable_while_typing = true
        tap-to-click         = true
        natural_scroll       = true
        scroll_factor        = 0.8
    }
}

# ── Gestures ───────────────────────────────
gestures {
    workspace_swipe_distance     = 300
    workspace_swipe_invert       = true
    workspace_swipe_cancel_ratio = 0.3
    workspace_swipe_create_new   = true
}

gesture = 3, horizontal, workspace

# ── Per-device config ───────────────────────
device {
    name        = epic-mouse-v1
    sensitivity = -0.5
}
