windowrulev2 = workspace 2, class:google-chrome
windowrulev2 = workspace 3, class:BambuStudio
windowrulev2 = workspace 4 silent, class:com.obsproject.Studio
windowrulev2 = workspace 3, class:discord

# Float all file chooser dialogs
windowrulev2 = float, title:^(Open File|Save File|Save As|Open Folder)$
windowrulev2 = float, class:^(xdg-desktop-portal|xdg-desktop-portal-gtk)$
windowrulev2 = float, class:^(waypaper)$
